---
name: logging-service

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

releases:
- name: ap-fluentd
  version: 1.15.2.1
  sha1: d5d07c0bfd9f9e37f1b8130b2212a7ea871c8e54
  url: https://nextcloud.k-paas.org/index.php/s/zDF3JiqXQ775FDp/download
- name: monitoring-influxdb
  version: 5.8.1.1
  sha1: b0ce403ad012bcb3730db9bba37254847d2c72bd
  url: https://nextcloud.k-paas.org/index.php/s/tk3YzjC5ijS77sM/download
- name: ap-collector
  version: 5.8.2.1
  sha1: dd074bf19e8838c5252bcd5f06827c8bb558704b
  url: https://nextcloud.k-paas.org/index.php/s/j3zDRp6kZERPNW5/download
- name: syslog
  version: 12.0.2
  sha1: ef0c0cfaf83002175fd88aae005774e33f1d4787
  url: https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=12.0.2
- name: bpm
  version: 1.1.15
  sha1: 0d48aa01a65b947b97570234eb2401e821a8bd35
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.15

instance_groups:
- name: fluentd
  azs: ((fluentd_azs))
  instances: ((fluentd_instances))
  vm_type: ((fluentd_vm_type))
  stemcell: default
  networks:
  - name: ((fluentd_network))
    static_ips:
    - ((fluentd_ip))
  jobs:
  - name: fluentd
    release: ap-fluentd
    properties:
      logging:
        db:
          name: ((influxdb_database))
        measurement:
          name: ((influxdb_measurement))
        time:
          precision: ((influxdb_time_precision))
      influxdb:
        http:
          host: ((influxdb_ip))
          port: ((influxdb_http_port))
        user: ((influxdb_username))
        password: ((influxdb_password))
        ssl:
          enabled: ((influxdb_https_enabled))
      fluentd:
        port: ((fluentd_port))
        transport: ((fluentd_transport))
  - name: bpm
    release: bpm

- name: influxdb
  azs: ((influxdb_azs))
  instances: ((influxdb_instances))
  vm_type: ((influxdb_vm_type))
  stemcell: default
  persistent_disk_type: ((influxdb_persistent_disk_type))
  networks:
  - name: ((influxdb_network))
    static_ips:
    - ((influxdb_ip))
  jobs:
  - name: influxdb
    release: monitoring-influxdb
    properties:
      influxdb:
        user: ((influxdb_username))
        password: ((influxdb_password))
        interval: ((influxdb_interval))
        replication: 1
        ips: 127.0.0.1
        https_enabled: ((influxdb_https_enabled))
        http:
          bind-address: ((influxdb_http_port))
        pem_key: ((influxdb_pem_key))
        logging_db_name: ((influxdb_database))
  - name: chronograf
    release: monitoring-influxdb
    properties:
      influxdb:
        user: ((influxdb_username))
        password: ((influxdb_password))
        https_enabled: ((influxdb_https_enabled))
        http:
          bind-address: ((influxdb_http_port))
  - name: bpm
    release: bpm

- name: collector
  azs: ((collector_azs))
  instances: ((collector_instances))
  vm_type: ((collector_vm_type))
  stemcell: default
  networks:
  - name: ((collector_network))
  jobs:
  - name: ingestor_cloudfoundry-firehose
    release: ap-collector
    properties:
      cloudfoundry:
        api_endpoint: https://api.((system_domain))
        firehose_client_id: firehose-to-syslog
        firehose_client_secret: firehose-secret
        firehose_events: LogMessage
        skip_ssl_validation: "true"
      create-uaa-client:
        cloudfoundry:
          system_domain: ((system_domain))
          uaa_admin_client_id: ((uaa_client_admin_id))
          uaa_admin_client_secret: ((uaa_client_admin_secret))
      syslog:
        host: ((fluentd_ip))
        port: ((fluentd_port))
        protocol: ((fluentd_transport))
  - name: syslog_forwarder
    release: syslog
    properties:
      syslog:
        address: ((fluentd_ip))
        custom_rule: |
          ((syslog_forwarder_custom_rule))
          if ($programname startswith "vcap.") then stop
        fallback_servers: ((syslog_forwarder_fallback_servers))
        port: ((fluentd_port))
        tls_enabled: false
        transport: ((fluentd_transport))


update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-600000
