---
name: logging-service

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

releases:
- name: paasta-portal-api-release
  sha1: e04ae6b2f796e78ebe3243d9f0325224a6979c99
  version: 2.5.10
  url: https://nextcloud.paas-ta.org/index.php/s/GiKm67pjZ3mRP2m/download
- name: monitoring-dashboard-release
  version: 5.8.1
  sha1: 59e6a10ff7ee11093fedcad0ede8e8265179b973
  url: https://nextcloud.paas-ta.org/index.php/s/DPKMAafeHwKNWs4/download
- name: monitoring-influxdb-release
  version: 5.8.1
  sha1: 813d7b2ebf18c0859df209853818c53a22f42b2f
  url: https://nextcloud.paas-ta.org/index.php/s/qSsJerfdNKXxC5o/download
- name: paasta-collector-release
  version: 5.8.2
  sha1: f56523758bc839be53e44583df1b65837ed303af
  url: https://nextcloud.paas-ta.org/index.php/s/gesnBRQsKEJPoTE/download
- name: syslog
  version: 12.0.2
  sha1: ef0c0cfaf83002175fd88aae005774e33f1d4787
  url: https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=12.0.2
- name: bpm
  version: 1.1.15
  sha1: 0d48aa01a65b947b97570234eb2401e821a8bd35
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.15

instance_groups:
- name: fluentd
  azs: ((fluentd_azs))
  instances: ((fluentd_instances))
  vm_type: ((fluentd_vm_type))
  stemcell: default
  networks:
  - name: ((fluentd_network))
    static_ips:
    - ((fluentd_ip))
  jobs:
  - name: fluentd
    release: monitoring-dashboard-release
    properties:
      logging:
        db:
          name: ((influxdb_database))
        measurement:
          name: ((influxdb_measurement))
        time:
          precision: ((influxdb_time_precision))
      influxdb:
        http:
          host: ((influxdb_ip))
          port: ((influxdb_http_port))
        user: ((influxdb_username))
        password: ((influxdb_password))
        ssl:
          enabled: false
      fluentd:
        port: ((fluentd_port))
        transport: ((fluentd_transport))
  - name: bpm
    release: bpm

- name: influxdb
  azs: ((influxdb_azs))
  instances: ((influxdb_instances))
  vm_type: ((influxdb_vm_type))
  stemcell: default
  persistent_disk_type: ((influxdb_persistent_disk_type))
  networks:
  - name: ((influxdb_network))
    static_ips:
    - ((influxdb_ip))
  jobs:
  - name: influxdb
    release: monitoring-influxdb-release
    properties:
      influxdb:
        user: ((influxdb_username))
        password: ((influxdb_password))
        interval: ((influxdb_interval)) 
        replication: 1
        ips: 127.0.0.1
        https_enabled: false
        http:
          bind-address: ((influxdb_http_port))
        pem_key: ((influxdb_ssl.certificate))((influxdb_ssl.private_key))
        logging_db_name: ((influxdb_database))
  - name: chronograf
    release: monitoring-influxdb-release
    properties:
      influxdb:
        user: ((influxdb_username))
        password: ((influxdb_password))
        https_enabled: false
        http:
          bind-address: ((influxdb_http_port))
  - name: bpm
    release: bpm

- name: collector
  azs: ((collector_azs))
  instances: ((collector_instances))
  vm_type: ((collector_vm_type))
  stemcell: default
  networks:
  - name: ((collector_network))
  jobs:
  - name: ingestor_cloudfoundry-firehose
    release: paasta-collector-release
    properties:
      cloudfoundry:
        api_endpoint: https://api.((system_domain))
        firehose_client_id: firehose-to-syslog
        firehose_client_secret: firehose-secret
        firehose_events: LogMessage
        skip_ssl_validation: true
      create-uaa-client:
        cloudfoundry:
          system_domain: ((system_domain))
          uaa_admin_client_id: ((uaa_client_admin_id))
          uaa_admin_client_secret: ((uaa_client_admin_secret))
      syslog:
        host: ((fluentd_ip))
        port: ((fluentd_port))
        protocol: ((fluentd_transport))
  - name: syslog_forwarder
    release: syslog
    properties:
      syslog:
        address: ((fluentd_ip))
        custom_rule: |
          ((syslog_forwarder_custom_rule))
          if ($programname startswith "vcap.") then stop
        fallback_servers: ((syslog_forwarder_fallback_servers))
        port: ((fluentd_port))
        tls_enabled: false
        transport: ((fluentd_transport))

- name : api
  azs: ((api_azs))
  instances: ((api_instances))
  vm_type: ((api_vm_type))
  stemcell: default
  networks:
  - name: ((api_network))
  jobs:
  - name: paas-ta-portal-log-api
    release: paasta-portal-api-release
    consumes:
      paas-ta-portal-registration-link: {from: portal-registration, deployment: portal-api}
  properties:
    influxdb:
      ip: ((influxdb_ip))
      port: ((influxdb_http_port))
      username: ((influxdb_username))
      password: ((influxdb_password))
      database: ((influxdb_database))
      measurement: ((influxdb_measurement))
      limit: ((influxdb_query_limit))


variables:
- name: influxdb_ca
  options:
    common_name: influxdbCA
    is_ca: true
  type: certificate
- name: influxdb_ssl
  options:
    alternative_names:
    - ((system_domain))
    - '*.((system_domain))'
    ca: influxdb_ca
    common_name: influxdbSSL
  type: certificate

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-600000
