# pinpoint 설정 파일 내용
name: pinpoint                                                    # 서비스 배포이름(필수)

releases:
- name: "ap-pinpoint"                                # 서비스 릴리즈 이름(필수) bosh releases로 확인 가능
  version: "1.1.5.1"                                              # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전
  sha1: b92988c68548962eba629575c1f45d417f0c41ae
  url: https://nextcloud.k-paas.org/index.php/s/W6N2TcGwekx5iz8/download

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))
  
update:
  canaries: 1                                                     # canary 인스턴스 수(필수)
  canary_watch_time: 120000                                       # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 120000                                       # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 8                                                # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)

instance_groups:
- name: h_master                                                  # 작업 이름(필수)
  azs: ((master_azs))
  instances: ((master_instances))                                 # job 인스턴스 수(필수)
  vm_type: ((master_vm_type))
  stemcell: default
  persistent_disk_type: ((master_persistent_disk_type))
  networks:                                                       # 네트워크 구성정보          
  - name: ((private_networks_name))                               # Networks block에서 선언한 network 이름(필수)
  jobs:
  - name: h_master
    release: "ap-pinpoint"
  syslog_aggregator: null
  provides:
    h_master_link: {as: h_master}
  consume:
    h_master_link: {from: h_master}

- name: collector                                                 # 작업 이름(필수)
  azs: ((collector_azs))
  instances: ((collector_instances))                              # job 인스턴스 수(필수)
  vm_type: ((collector_vm_type))
  stemcell: default
  persistent_disk_type: ((collector_persistent_disk_type))
  networks:                                                       # 네트워크 구성정보          
  - name: ((private_networks_name))                            # Networks block에서 선언한 network 이름(필수)
  jobs:
  - name: collector 
    release: "ap-pinpoint"
  syslog_aggregator: null
  provides:
    collector_link: {as: collector}
  consume:
    h_master_link: {from: h_master}
    collector_link: {from: collector}

- name: pinpoint_web                                              # 작업 이름(필수)
  azs: ((pinpoint_azs))
  instances: ((pinpoint_instances))                               # job 인스턴스 수(필수)
  vm_type: ((pinpoint_vm_type))
  stemcell: default
  persistent_disk_type: ((pinpoint_persistent_disk_type))
  networks:                                                       # 네트워크 구성정보          
  - name: ((private_networks_name))                             # Networks block에서 선언한 network 이름(필수)
  jobs:
  - name: pinpoint_web
    release: "ap-pinpoint"
  syslog_aggregator: null
  provides:
    pinpoint_web_link: {as: pinpoint_web}
  consume:
    h_master_link: {from: h_master}
    pinpoint_web_link: {from: pinpoint_web}

- name: service-broker                                                    # 작업 이름(필수)
  azs: ((broker_azs))
  instances: ((broker_instances))                                 # job 인스턴스 수(필수)
  vm_type: ((broker_vm_type))
  stemcell: default
  persistent_disk_type: ((broker_persistent_disk_type))
  networks:                                                       # 네트워크 구성정보          
  - name: ((private_networks_name))                               # Networks block에서 선언한 network 이름(필수)
  jobs:
  - name: ap-pinpoint-broker
    release: "ap-pinpoint"
  syslog_aggregator: null
  provides:
    broker_link: {as: broker}
  consume:
    collector_link: {from: collector}
    broker_link: {from: broker}

- name: haproxy_webui                                             # 작업 이름(필수)
  azs: ((webui_azs))
  instances: ((webui_instances))                                  # job 인스턴스 수(필수)
  vm_type: ((webui_vm_type))
  stemcell: default
  persistent_disk_type: ((webui_persistent_disk_type))
  networks:                                                       # 네트워크 구성정보          
  - name: ((private_networks_name))                       # Networks block에서 선언한 network 이름(필수)
  - name: ((public_networks_name))
    static_ips: ((webui_haproxy_public_ip))
  jobs:
  - name: haproxy_webui
    release: "ap-pinpoint"
  syslog_aggregator: null
  provides:
    haproxy_link: {as: haproxy_webui}
  consume:
    pinpoint_web_link: {from: pinpoint_web}

properties:                                                       # Pinpoint 설정정보
  broker:                                                         # Pinpoint broker 설정정보
    collector_tcp_port: ((collector_tcp_port))                    # Pinpoint collector tcp port 설정정보
    collector_stat_port: ((collector_stat_port))                  # Pinpoint collector stat port 설정정보
    collector_span_port: ((collector_span_port))                  # Pinpoint collector span port 설정정보
    dashboard_uri: http://((webui_haproxy_public_ip)):80/#/main   # Pinpoint dashboard url 설정정보
  cce_enable: false
