---
name: rabbitmq

instance_groups:
- azs: ((broker_azs))
  instances: ((broker_instances))
  jobs:
  - name: rabbitmq-service-broker
    properties:
      cf:
        domain: ((system_domain))
      rabbitmq-service-broker:
        cc_endpoint: http://api.((system_domain))
        logging:
          level: debug
          print_stack_traces: false
        rabbitmq:
          administrator:
            password: ((administrator_password))
            username: ((administrator_username))
          hosts: USING BOSH LINKS
          management:
            username: ((management_username))
          management_domain: server.rmq.((system_domain))
          operator_set_policy:
            enabled: true
            policy_definition: '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
            policy_name: operator_set_policy
            policy_priority: 50
        route: broker-rmq
        service:
          name: rabbitmq
          password: ((broker_password))
          plan_uuid: 22F0B28C-B886-4123-B01B-95E54D3DE6DA
          shareable: true
          username: ((broker_username))
          uuid: 568725FD-AD46-44CA-9853-621416E983A4
    release: paasta-rabbitmq
  name: rmq-broker
  networks:
  - name: ((private_networks_name)) 
  stemcell: default
  vm_type: ((vm_type_small)) 
- azs: ((rabbitmq_azs))
  instances: ((rabbitmq_instances))
  jobs:
  - name: rabbitmq-server
    properties:
      rabbitmq-server:
        administrators:
          broker:
            password: ((administrator_password))
            username: ((administrator_username))
          management:
            password: ((management_password))
            username: ((management_username))
        cluster_partition_handling: autoheal
        cookie: rabbit-cluster:aws
        disk_alarm_threshold: '{mem_relative,0.4}'
        plugins:
        - rabbitmq_management
        - rabbitmq_mqtt
        - rabbitmq_stomp
        ports:
        - 5672
        - 5671
        - 1883
        - 8883
        - 61613
        - 61614
        - 15672
        - 15674
        restart_statsdb_cron_schedule: 42 */4 * * *
    release: paasta-rabbitmq
  - name: route_registrar
    release: routing
    consumes:
      nats: {from: nats, deployment: paasta}
    properties:
      nats:
        tls:
          client_cert: "((nats_client_cert.certificate))"
          client_key: "((nats_client_cert.private_key))"
        machines: ["((paasta_nats_ip))"]
      route_registrar:
        routes:
        - name: server-rmq
          port: 15672
          registration_interval: 20s
          uris:
          - server.rmq.((system_domain))
  - name: bpm
    release: bpm
  name: rmq
  networks:
  - name: ((private_networks_name)) 
    static_ips: ((rabbitmq_private_ips))
  persistent_disk_type: 50GB
  stemcell: default 
  vm_type: ((vm_type_small))  
- azs: ((haproxy_azs))
  instances: ((haproxy_instances)) 
  jobs:
  - name: rabbitmq-haproxy
    properties:
      rabbitmq-haproxy:
        stats:
          password: ((management_password))
          username: ((management_username))
    release: paasta-rabbitmq
  name: haproxy
  networks:
  - name: ((private_networks_name)) 
    static_ips: ((haproxy_private_ips))
  stemcell: default 
  vm_type: ((vm_type_small)) 

releases:
- name: bpm
  version: latest
- name: paasta-rabbitmq
  url: https://nextcloud.paas-ta.org/index.php/s/o4HQoeYbEKPdNma/download
  version: 2.1.0
- name: routing
  url: https://bosh.io/d/github.com/cloudfoundry/routing-release?v=0.207.0
  version: 0.207.0
  sha1: 9e703259a07f032e7ca96dca2730d0e0c2b61685

variables:
- name: administrator_password
  type: password
- name: management_password
  type: password
- name: nats_ca
  type: certificate
  options:
    is_ca: true
    common_name: nats
- name: nats_client_cert
  type: certificate
  options:
    ca: nats_ca
    common_name: "nats_client"
    extended_key_usage:
    - client_auth

stemcells:
- alias: default 
  os: ((stemcell_os))
  version: ((stemcell_version))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
  update_watch_time: 30000-180000

