---
name: rabbitmq

instance_groups:
- azs: ((broker_azs))
  instances: ((broker_instances))
  jobs:
  - name: rabbitmq-service-broker
    properties:
      cf:
        domain: ((system_domain))
      rabbitmq-service-broker:
        cc_endpoint: http://api.((system_domain))
        logging:
          level: debug
          print_stack_traces: false
        rabbitmq:
          administrator:
            password: ((broker_password))
            username: ((broker_username))
          hosts: USING BOSH LINKS
          management:
            username: ((management_username))
          management_domain: paaasta-rabbitmq.((system_domain))
          operator_set_policy:
            enabled: true
            policy_definition: '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
            policy_name: operator_set_policy
            policy_priority: 50
        route: rabbitmq-multitenant-broker
        service:
          name: rabbitmq
          password: ((broker_password))
          plan_uuid: 22F0B28C-B886-4123-B01B-95E54D3DE6DA
          shareable: true
          username: ((broker_username))
          uuid: 568725FD-AD46-44CA-9853-621416E983A4
    release: paasta-rabbitmq
  - name: bpm
    release: bpm
  - name: broker-registrar
    properties:
      broker:
        host: rabbitmq-broker.((system_domain))
        port: ((broker_port))
        name: rabbitmq
        password: ((broker_password))
        protocol: http
        service:
          name: rabbitmq
        username: ((broker_username))
      cf:
        admin_password: ((paasta_admin_password)) 
        admin_username: ((paasta_admin_username))
        api_url: https://api.((system_domain))
    release: paasta-rabbitmq
  - name: broker-deregistrar
    properties:
      broker:
        name: rabbitmq
        service:
          name: rabbitmq
      cf:
        admin_password: ((paasta_admin_password)) 
        admin_username: ((paasta_admin_username))
        api_url: https://api.((system_domain))
    release: paasta-rabbitmq
  name: rmq-broker
  networks:
  - name: ((private_networks_name)) 
  stemcell: default
  vm_type: ((vm_type_small)) 
- azs: ((rabbitmq_azs))
  instances: ((rabbitmq_instances))
  jobs:
  - name: rabbitmq-server
    properties:
      rabbitmq-server:
        administrators:
          broker:
            password: ((broker_password))
            username: ((broker_username))
          management:
            password: ((management_password))
            username: ((management_username))
        cluster_partition_handling: autoheal
        cookie: rabbit-cluster:aws
        disk_alarm_threshold: '{mem_relative,0.4}'
        plugins:
        - rabbitmq_management
        - rabbitmq_mqtt
        - rabbitmq_stomp
        ports:
        - 5672
        - 5671
        - 1883
        - 8883
        - 61613
        - 61614
        - 15672
        - 15674
        restart_statsdb_cron_schedule: 42 */4 * * *
    release: paasta-rabbitmq
  name: rmq
  networks:
  - name: ((private_networks_name)) 
  persistent_disk_type: 50GB
  stemcell: default 
  vm_type: ((vm_type_small))  
- azs: ((haproxy_azs))
  instances: ((haproxy_instances)) 
  jobs:
  - name: rabbitmq-haproxy
    properties:
      rabbitmq-haproxy:
        stats:
          password: ((management_password)
          username: ((management_username))
    release: paasta-rabbitmq
  - name: bpm
    release: bpm
  name: haproxy
  networks:
  - name: ((private_networks_name)) 
  stemcell: default 
  vm_type: ((vm_type_small)) 

releases:
- name: cf-cli
  version: latest
- name: bpm
  version: latest
- name: paasta-rabbitmq
  url: https://nextcloud.paas-ta.org/index.php/s/o4HQoeYbEKPdNma/download
  version: 2.1.0

variables:
- name: administar_password
  type: password

stemcells:
- alias: default 
  os: ((stemcell_os))
  version: ((stemcell_version))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
  update_watch_time: 30000-180000
