# mongodb 설정 파일 내용
name: mongodb  # 서비스 배포이름(필수)

releases:
- name: paasta-mongodb-shard  #서비스 릴리즈 이름(필수)
  url: https://nextcloud.paas-ta.org/index.php/s/WQNz4g56ao2gqtW/download 
  version: "2.1.3"   #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

# this section describes how updates are handled
update:
  canaries: 1   # canary 인스턴스 수(필수)
  canary_watch_time: 120000  # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 120000  # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  max_in_flight: 4

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

instance_groups:
- name: mongodb_slave1  #작업 이름(필수): mongodb replica set의 slave 서버
  instances: ((mongodb_slave1_instances))  # job 인스턴스 수(필수)
  vm_type: ((mongodb_slave1_vm_type))
  stemcell: default
  persistent_disk_type: ((mongodb_slave1_persistent_disk_type))  # 영구적 디스크 사이즈 정의(옵션): 16G
  azs: ((mongodb_slave1_azs))
  networks:   # 네트워크 구성정보
  - name: ((private_networks_name))   # Networks block에서 선언한 network 이름(필수)
    static_ips: ((mongodb_slave1_static_ips))  # 사용할 IP addresses 정의(필수)
  jobs:
  - name: mongodb_slave
    properties:
      replSetName: ((replSetName1)) # replicaSet1 의 이름
      mongodb:
        key: ((key))
    release: paasta-mongodb-shard
- name: mongodb_slave2
  vm_type: ((mongodb_slave2_vm_type))
  stemcell: default
  azs: ((mongodb_slave2_azs))
  instances: ((mongodb_slave2_instances))
  persistent_disk_type: ((mongodb_slave2_persistent_disk_type))
  networks:
  - name: ((private_networks_name))
    static_ips: ((mongodb_slave2_static_ips))
  jobs:
  - name: mongodb_slave
    properties:
      replSetName: ((replSetName2)) # replicaSet2 의 이름
      mongodb:
        key: ((key))
    release: paasta-mongodb-shard
- name: mongodb_master1   #작업 이름(필수): mongodb replica set의 master 서버
  instances: ((mongodb_master1_instances))  # job 인스턴스 수(필수)
  azs: ((mongodb_master1_azs))
  stemcell: default
  vm_type: ((mongodb_master1_vm_type))
  persistent_disk_type: ((mongodb_master1_persistent_disk_type))  # 영구적 디스크 사이즈 정의(옵션): 16G
  networks:   # 네트워크 구성정보
  - name: ((private_networks_name))   # Networks block에서 선언한 network 이름(필수)
    static_ips: [((mongodb_master1_static_ips))]   # 사용할 IP addresses 정의(필수)
  jobs:
  - name: mongodb_master
    properties:
      replSet_hosts: ((mongodb_master1_replSet_hosts)) # 첫번째 Host는 replicaSet1의 master
      replSetName: ((replSetName1)) # replicaSet1 의 이름
      mongodb:
        key: ((key))
    release: paasta-mongodb-shard
- name: mongodb_master2
  azs: ((mongodb_master2_azs))
  instances: ((mongodb_master2_instances))
  vm_type: ((mongodb_master2_vm_type))
  persistent_disk_type: ((mongodb_master2_persistent_disk_type))
  stemcell: default
  networks:
  - name: ((private_networks_name))
    static_ips: [((mongodb_master2_static_ips))]
  jobs:
  - name: mongodb_master
    properties:
      replSet_hosts: ((mongodb_master2_replSet_hosts)) # 첫번째 Host는 replicaSet2의 master
      replSetName: ((replSetName2))  # replicaSet2 의 이름
      mongodb:
        key: ((key))
    release: paasta-mongodb-shard
- name: mongodb_config
  azs: ((mongodb_config_azs))
  stemcell: default
  vm_type: ((mongodb_config_vm_type))
  instances: ((mongodb_config_instances))
  persistent_disk_type: ((mongodb_config_persistent_disk_type))
  networks:
  - name: ((private_networks_name))
    static_ips: ((mongodb_config_static_ips))
  jobs:
  - name: mongodb_config
    properties:
      mongodb:
        key: ((key))
      configsvr_hosts: ((mongodb_config_static_ips)) # mongodb_config hosts
    release: paasta-mongodb-shard
- name: mongodb_shard
  vm_type: ((mongodb_shard_vm_type))
  stemcell: default
  azs: ((mongodb_shard_azs))
  instances: ((mongodb_shard_instances))
  networks:
  - name: ((private_networks_name))
    static_ips: [((mongodb_shard_static_ips))]
  jobs:
  - name: mongodb_shard
    properties:
      mongodb:
        key: ((key))
      configsvr_hosts: ((mongodb_config_static_ips)) # mongodb_config hosts
      repl_name_host_list: # mongodb_master properties
      - ((replSetName1))/((mongodb_master1_static_ips)) # replicaSet1 의 이름/host
      - ((replSetName2))/((mongodb_master2_static_ips)) # replicaSet2 의 이름/host
    release: paasta-mongodb-shard
- name: mongodb_broker  #작업 이름(필수): mongodb 서비스 브로커
  vm_type: ((mongodb_broker_vm_type))
  stemcell: default
  azs: ((mongodb_broker_azs))
  instances: ((mongodb_broker_instances))  # job 인스턴스 수(필수)
  networks:   # 네트워크 구성정보
  - name: ((private_networks_name))   # Networks block에서 선언한 network 이름(필수)
    static_ips: ((mongodb_broker_static_ips))  # 사용할 IP addresses 정의(필수)
  jobs:
  - name: mongodb_broker
    release: paasta-mongodb-shard
- name : mongodb_broker_registrar   # 작업 이름: 서비스 브로커 등록
  azs: ((broker_registrar_broker_azs))
  stemcell: default
  vm_type: ((broker_registrar_broker_vm_type))
  instances: ((broker_registrar_broker_instances))
  lifecycle: errand   # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로 실행할때 설정, 주로 테스트 용도에 쓰임
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: mongodb_broker_registrar
    properties:
      broker:   # 서비스 브로커 설정 정보
        host: ((mongodb_broker_static_ips))   # 서비스 브로커 IP
        name: Mongo-DB  # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
        password: cloudfoundry  # 브로커 접근 아이디 비밀번호(필수)
        username: admin   # 브로커 접근 아이디(필수)
        protocol: http
        port: 8080  # 브로커 포트
      cf:
        admin_password: ((paasta_admin_password))   # CF 사용자의 패스워드
        admin_username: ((paasta_admin_username))   # CF 사용자 이름
        api_url: https://api.((system_domain))  # CF 설치시 설정한 api uri 정보(필수)
    release: paasta-mongodb-shard
- name : mongodb_broker_deregistrar   # 작업 이름: 서비스 브로커 삭제
  azs: ((broker_deregistrar_broker_azs))
  stemcell: default
  vm_type: ((broker_deregistrar_broker_vm_type))
  instances: ((broker_deregistrar_broker_instances))
  lifecycle: errand
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: mongodb_broker_deregistrar
    properties:
      broker:
        host: ((mongodb_broker_static_ips))
        name: Mongo-DB
        password: cloudfoundry
        username: admin
        protocol: http
        port: 8080
      cf:
        admin_password: ((paasta_admin_password))
        admin_username: ((paasta_admin_username))
        api_url: https://api.((system_domain))
    release: paasta-mongodb-shard

properties:
  mongodb:
    key: ((key))
    user: "root"  # admin 권한 사용자이름. Don't update.
    passwd: "openpaas"  # admin 권한 사용자 비밀번호. Don't update.
    port: "27017"   # mongodb port. Don't update.
  mongodb_broker:
    db_name: mongodb-broker # mongodb broker 관리용 데이터베이스
    authsource: admin   # mongodb broker 관리용 데이터베이스에 접근할 때 인증정보가 있는 데이터베이스
    hosts: ((mongodb_shard_static_ips)) # mongodb Host


meta:
  apps_domain: ((system_domain))   # CF 설치시 설정한 apps 도메인 정보
  environment: null
  external_domain: ((system_domain))   # CF 설치시 설정한 외부 도메인 정보
  nats:   # CF 설치시 설정한 nats 정보
    machines:
    - ((paasta_nats_ip))
    password: ((paasta_nats_password))
    port: ((paasta_nats_port))
    user: ((paasta_nats_user))
  syslog_aggregator: null
