# paasta-cubrid-service 설정 파일 내용
name: cubrid                               # 서비스 배포이름(필수)

releases:
- name: "paasta-cubrid"                    #서비스 릴리즈 이름(필수)
  version: "2.0.1"                           #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전
  url: https://nextcloud.paas-ta.org/index.php/s/ic6tB9gcgdL3XQK/download

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

update:
  canaries: 1                               # canary 인스턴스 수(필수)
  canary_watch_time: 30000-180000           # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 6                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-180000           # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)

instance_groups:
- name: cubrid                              #작업 이름(필수): Cubrid 서버
  azs: ((cubrid_azs))
  instances: ((cubrid_instances))           # job 인스턴스 수(필수)
  vm_type: ((cubrid_vm_type))               # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((private_networks_name))           # cloud config 에 정의한 network 이름
  jobs:
  - name: cubrid
    release: "paasta-cubrid"
    properties:
      cubrid:
        max_clients: ((cubrid_max_clients))
        certificate: "((cubrid_certificate.public_key))"
        private_key: "((cubrid_certificate.private_key))"

- name: cubrid_broker                       #작업 이름(필수): Cubrid 서비스 브로커
  azs: ((cubrid_broker_azs))
  instances: ((cubrid_broker_instances))    # job 인스턴스 수(필수)
  vm_type: ((cubrid_broker_vm_type))        # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((private_networks_name))    # cloud config 에 정의한 network 이름
  jobs:
  - name: cubrid_broker                     # job template 이름(필수)
    release: "paasta-cubrid"
    properties:
      cubrid:                                   # Cubrid 설정 정보
        private_key: "((cubrid_certificate.private_key))"
      cubrid_broker:                            # Cubrid Servcice Broker 설정 정보
        cubrid_db_port: ((cubrid_db_port))      # Cubrid Port
        cubrid_db_name: ((cubrid_db_name))      # Cubrid service 관리를 위한 데이터베이스 이름
        cubrid_db_user: ((cubrid_db_user))      # 브로커 관리용 데이터베이스 접근 사용자이름
        cubrid_db_passwd: ((cubrid_db_passwd))  # 브로커 관리용 데이터베이스 접근 사용자 비밀번호
        cubrid_ssh_port: ((cubrid_ssh_port))    # Cubrid가 설치된 서버 SSH 접속 포트
        cubrid_ssh_user: ((cubrid_ssh_user))    # Cubrid가 설치된 서버 SSH 접속 사용자 이름

variables:
- name: cubrid_certificate
  type: ssh
