---
name: marketplace                             # 서비스 배포이름(필수) bosh deployments 로 확인 가능한 이름

releases:
- name: paasta-marketplace-env-release
  url: http://45.248.73.44/index.php/s/S9S6YFcQrppcFPX/download 
  version: "1.1"

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

update:
  canaries: 1                                               # canary 인스턴스 수(필수)
  canary_watch_time: 5000-120000                            # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-120000                            # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false

instance_groups:
- name: binary_storage
  azs: ((object_storage_azs))
  instances: ((object_storage_instances))
  stemcell: default
  persistent_disk_type: ((object_storage_persistent_disk_type)) 
  vm_type: ((object_storage_vm_type))
  networks:
  - name: ((private_networks_name))
    default: [dns, gateway]
  - name: ((public_networks_name))
    static_ips: ((object_storage_public_static_ips))                             # Object Storage 의 public_IP(아래 properties.binary_storage.proxy_ip 와 동일)
  jobs:
  - name: binary_storage
    release: paasta-marketplace-env-release
- name: mariadb
  azs: ((mariadb_azs))
  instances: ((mariadb_instances))
  stemcell: default
  persistent_disk_type: ((maraidb_persistent_disk_type))
  vm_type: ((mariadb_vm_type))
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: mariadb
    release: paasta-marketplace-env-release

######### PROPERTIES ##########
properties:
  mariadb:                                                 # MARIA DB SERVER 설정 정보
    port: ((mariadb_port))
    admin_user:
      password: ((mariadb_admin_password))                 # MARIA DB ADMIN USER PASSWORD
  binary_storage:                                          # BINARY STORAGE SERVER 설정 정보
    proxy_ip: ((object_storage_public_static_ips))         # Object Storage 의 public_IP
    proxy_port: 10008                                      # 프록시 서버 Port(Object Storage 접속 Port)
    auth_port: ((object_storage_auth_port))
    username:                                              # 최초 생성되는 유저이름(Object Storage 접속 유저이름)
      - ((object_storage_username))
    password:                                              # 최초 생성되는 유저 비밀번호(Object Storage 접속 유저 비밀번호)
      - ((object_storage_password))
    tenantname:                                            # 최초 생성되는 테넌트 이름(Object Storage 접속 테넌트 이름)
      - ((object_storage_tenantname))
    email:                                                 # 최소 생성되는 유저의 이메일
      - ((object_storage_email))
    binary_desc:                                           # objectStorage_swift_container
      - ((object_storage_container))
