name: mysql

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

releases:
- name: paasta-mysql
  url: https://nextcloud.paas-ta.org/index.php/s/2YRA33Co9b3fq5L/download
  version: "2.1.1"
- name: bpm
  version: latest
stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: mysql
  instances: ((mysql_instances))
  azs: ((mysql_azs))
  networks:
  - name: ((private_networks_name))
  vm_type: ((mysql_vm_type))
  stemcell: default
  persistent_disk_type: ((mysql_persistent_disk_type))
  jobs:
  - name: mysql
    release: paasta-mysql
    properties:
      cf_mysql:
        mysql:
          port: ((mysql_port))
          admin_password: ((mysql_admin_password))
          cluster_health:
            password: "((mysql_cluster_health_password))"
          galera_healthcheck:
            endpoint_password: "((mysql_galera_healthcheck_endpoint_password))"
            db_password: "((mysql_galera_healthcheck_db_password))"
  - name: smoke-tests-user
    release: paasta-mysql
    properties:
      cf_mysql:
        smoke_tests:
          db_password: "((mysql_smoke_tests_db_password))"

- name: arbitrator
  instances: ((arbitrator_instances))
  azs: ((arbitrator_azs))
  networks:
  - name: ((private_networks_name))
  vm_type: ((arbitrator_vm_type))
  stemcell: default
  jobs:
  - release: paasta-mysql
    name: arbitrator
    properties:
      cf_mysql:
        mysql:
          admin_password: ((mysql_admin_password))
          galera_healthcheck:
            endpoint_password: "((mysql_galera_healthcheck_endpoint_password))"

- name: proxy
  instances: ((proxy_instances))
  azs: ((proxy_azs))
  networks:
  - name: ((private_networks_name))
  vm_type: ((proxy_vm_type))
  stemcell: default
  jobs:
  - name: proxy
    release: paasta-mysql
    properties:
      cf_mysql:
        proxy:
          port: ((proxy_mysql_port))
          api_password: "((proxy_api_password))"
    provides:
      mysql-database:
        as: mysql-database
        shared: true

- name: mysql-broker
  instances: ((mysql_broker_instances))
  azs: ((mysql_broker_azs))
  networks:
  - name: ((private_networks_name))
  vm_type: ((mysql_broker_vm_type))
  stemcell: default
  jobs:
  - name: op-mysql-java-broker
    release: paasta-mysql
    properties:
      log_dir: mysql-broker
      log_file: mysql-broker
      log_level: INFO

variables:
- name: mysql_cluster_health_password
  type: password
- name: mysql_galera_healthcheck_endpoint_password
  type: password
- name: mysql_galera_healthcheck_db_password
  type: password
- name: mysql_smoke_tests_db_password
  type: password  
- name: proxy_api_password
  type: password
