name: mysql

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

releases:
- name: "pxc"
  sha1: 495099d35e3b2a24bf73ed42c152e1ff10cb3576
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/pxc-release?v=0.44.0
  version: 0.44.0
- name: paasta-conf
  url:  https://nextcloud.paas-ta.org/index.php/s/2zz3xPqEErCPq3y/download
  version: 1.0.7
- name: paasta-mysql
  sha1: 697bc5283b1cfec20764a70f6bfda82b882fff40
  url: https://nextcloud.paas-ta.org/index.php/s/wLDLEd5X4S2RrXP/download
  version: 2.2.1

- name: bpm
  version: latest
 
stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

#features:
#  use_dns_addresses: false

instance_groups:
- name: mysql
  migrated_from:
  - name: mysql
  azs: ((mysql_azs))
  persistent_disk_type: ((mysql_persistent_disk_type))
  instances: ((mysql_instances))
  vm_type: ((mysql_vm_type))
  stemcell: default
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: pxc-mysql
    release: pxc
    properties:
      admin_password: ((mysql_admin_password))
      engine_config:
        binlog:
          enabled: false
        galera:
          enabled: true
      port: ((mysql_port))
      tls:
        galera: ((galera_server_certificate))
        server: ((mysql_server_certificate))
  - name: galera-agent
    release: pxc
    properties:
      db_password: ((cf_mysql_mysql_galera_healthcheck_password))
      endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))
  - name: gra-log-purger
    release: pxc
  - name: cluster-health-logger
    release: pxc
    properties:
      db_password: ((cf_mysql_mysql_cluster_health_password))
  - name: bootstrap
    release: pxc
  - name: db_init_script
    release: paasta-conf
    properties:
      delay_time: 10
      db_client_path: /var/vcap/packages/pxc/bin/mysql
      db_username: root
      db_password: ((mysql_admin_password))
      socket_path: /var/vcap/sys/run/pxc-mysql/mysqld.sock
      database_type: mysql
      init_sql: |-
        CREATE DATABASE IF NOT EXISTS broker;
        USE broker;
        CREATE TABLE IF NOT EXISTS `service_binding` (
          `binding_id` varchar(100) NOT NULL DEFAULT '',
          `instance_id` varchar(100) DEFAULT NULL,
          `username` varchar(100) DEFAULT NULL,
          `password` varchar(100) DEFAULT NULL,
          `app_id` varchar(100) DEFAULT NULL,
          PRIMARY KEY (`binding_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

        CREATE TABLE IF NOT EXISTS `service_instances` (
          `instance_id` varchar(100) NOT NULL,
          `service_id` varchar(100) NOT NULL,
          `plan_id` varchar(100) NOT NULL,
          `organization_guid` varchar(100) NOT NULL,
          `space_guid` varchar(100) NOT NULL,
          PRIMARY KEY (`instance_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

        CREATE USER IF NOT EXISTS 'root'@'((proxy_static_ip))' IDENTIFIED BY '((mysql_admin_password))';
        ALTER USER IF EXISTS 'root'@'((proxy_static_ip))' IDENTIFIED BY '((mysql_admin_password))';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'((proxy_static_ip))' WITH GRANT OPTION;
        flush privileges;



- name: proxy
  instances: 1
  azs: ((proxy_azs))
  networks:
  - name: ((private_networks_name))
    static_ips: [((proxy_static_ip))]
  vm_type: ((proxy_vm_type))
  stemcell: default
  jobs:
  - name: proxy
    release: pxc
    properties:
      port: ((proxy_mysql_port))
      api_password: ((cf_mysql_proxy_api_password))
      api_port: 8083

- name: mysql-broker
  instances: ((mysql_broker_instances))
  azs: ((mysql_broker_azs))
  networks:
  - name: ((private_networks_name))
  vm_type: ((mysql_broker_vm_type))
  stemcell: default
  jobs:
  - name: op-mysql-java-broker
    release: paasta-mysql
    properties:
      database_type: mysql
      mysql_admin_password: ((mysql_admin_password))
      log_dir: mysql-broker
      log_file: mysql-broker
      log_level: INFO
      services:
        plans:
          a:
            name: ((mysql_broker_services_plan_a_name))
            connection: ((mysql_broker_services_plan_a_connection))
          b:
            name: ((mysql_broker_services_plan_b_name))
            connection: ((mysql_broker_services_plan_b_connection))

variables:
- name: cf_mysql_mysql_admin_password
  type: password
- name: cf_mysql_proxy_api_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_endpoint_password
  type: password
- name: cf_mysql_mysql_cluster_health_password
  type: password
- name: pxc_galera_ca
  type: certificate
  options:
    common_name: pxc_galera_ca
    is_ca: true
- name: pxc_server_ca
  type: certificate
  options:
    common_name: pxc_server_ca
    is_ca: true
- name: galera_server_certificate
  type: certificate
  update_mode: converge
  options:
    ca: pxc_galera_ca
    common_name: galera_server_certificate
    alternative_names:
    - galera_server_certificate
    extended_key_usage:
    - server_auth
    - client_auth
- name: mysql_server_certificate
  type: certificate
  update_mode: converge
  options:
    ca: pxc_server_ca
    common_name: sql-db.service.cf.internal
    alternative_names:
    - sql-db.service.cf.internal

