---
name: ((deployment_name))
features:
  use_dns_addresses: false
releases:
- name: ap-app-lifecycle
  url: https://nextcloud.k-paas.org/index.php/s/y4ntzqsjDNyQXKb/download
  sha1: c1e0f44feb1b0f57e44e9c2dbb1675d8811238f9
  version: "1.1.7.1"

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: true

instance_groups:
- name: mariadb
  azs: ((mariadb_azs))
  instances: ((mariadb_instances))
  persistent_disk_type: ((mariadb_persistent_disk_type))
  vm_type: ((vm_type_default))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: mariadb
    release: ap-app-lifecycle
    properties:
      database:
        port: ((mariadb_port))
        admin_password: ((mariadb_admin_password))
        broker:
          username: ((mariadb_broker_username))
          password: ((mariadb_broker_password))
  update:
    max_in_flight: 1

- name: service-broker
  azs: ((broker_azs))
  instances: ((broker_instances))
  vm_type: ((vm_type_default))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: ap-app-lifecycle-broker
    release: ap-app-lifecycle
    properties:
      bosh:
        client:
          id: ((bosh_client_admin_id))
          secret: ((bosh_client_admin_secret))
        url: ((bosh_url)):((bosh_director_port))
        oauth_url: ((bosh_url)):((bosh_oauth_port))
        deployment_name: ((deployment_name))
      port: ((broker_port))
      logging:
        level_broker: ((broker_logging_level_broker))
        level_hibernate: ((broker_logging_level_hibernate))
      service:
        init_password: ((app_lifecycle_serviceadmin_password))
      services:
        name: "app-lifecycle"
        id: ((broker_services_id))
        plans:
          id: ((broker_services_plans_id))
  update:
    max_in_flight: 1

- name: app-lifecycle
  azs: ((app_lifecycle_azs))
  instances: ((app_lifecycle_instances))
  persistent_disk_type: ((app_lifecycle_persistent_disk_type))
  vm_type: ((vm_type_default))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  - name: ((public_networks_name))
  jobs:
  - name: taiga-front
    release: ap-app-lifecycle
  - name: taiga-back
    release: ap-app-lifecycle
    properties:
      service:
        admin_password: ((app_lifecycle_admin_password))
        init_password: ((app_lifecycle_serviceadmin_password))
  - name: postgres
    release: ap-app-lifecycle
    properties:
      service:
        admin_password: ((app_lifecycle_admin_password))
        init_password: ((app_lifecycle_serviceadmin_password))
  update:
    max_in_flight: 1
