name: redis                                   #서비스 배포이름(필수) bosh deployments 로 확인 가능한 이름

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

variables:
- name: redis-password
  type: password

releases:
- name: bpm
  version: latest
- name: "paasta-on-demand-redis-release"                    # 서비스 릴리즈 이름(필수) bosh releases로 확인 가능
  version: "1.2.7"                                            # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전
  sha1: a22d94e6fcbaf34605f887941f7f956eb754feb1
  url: https://nextcloud.paas-ta.org/index.php/s/En6fBAtDbnWrads/download

update:
  canaries: 1                                               # canary 인스턴스 수(필수)
  canary_watch_time: 5000-120000                            # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-120000                            # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false

instance_groups:
########## INFRA ##########
- name: mariadb
  azs: ((mariadb_azs))
  instances: ((mariadb_instances))
  vm_type: ((mariadb_vm_type)) 
  stemcell: default
  persistent_disk_type: ((mariadb_persistent_disk_type))
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: mariadb
    release: "paasta-on-demand-redis-release"
  syslog_aggregator: null

######## BROKER ########
- name: paas-ta-on-demand-broker
  azs: ((broker_azs))
  instances: ((broker_instances))
  vm_type: ((broker_vm_type))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: paas-ta-on-demand-broker
    release: "paasta-on-demand-redis-release"
  syslog_aggregator: null
  
- name: redis
  azs: ((redis_azs))
  instances: 0 
  vm_type: ((redis_vm_type))
  stemcell: default
  persistent_disk_type: ((redis_persistent_disk_type))
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: redis
    release: "paasta-on-demand-redis-release"
    properties:
      cce_enable: false
      service: 
        port: ((service_port))
        password: ((service_password))
- name: sanity-tests
  azs: ((sanity_tests_azs))
  instances: ((sanity_tests_instances))
  lifecycle: errand
  vm_type: ((sanity_tests_vm_type))
  stemcell: default
  networks: 
  - name: ((private_networks_name))
  jobs:
  - name: sanity-tests
    release: "paasta-on-demand-redis-release"

######### COMMON PROPERTIES ##########
properties:
  broker:
    server:
      port: ((broker_server_port))
    datasource:
      password: ((mariadb_user_password))
    service_instance:
      guid: ((service_instance_guid))
      name: ((service_instance_name))
      bullet:
        name: ((service_instance_bullet_name))
        desc: ((service_instance_bullet_desc))
      plan: 
        id: ((service_instance_plan_guid))
        name: ((service_instance_plan_name))
        desc: ((service_instance_plan_desc))
      org_limitation: ((service_instance_org_limitation))
      space_limitation: ((service_instance_space_limitation))
    bosh:
      client_id: ((bosh_client_admin_id))
      client_secret: ((bosh_client_admin_secret))
      url: ((bosh_url)):((bosh_director_port))
      oauth_url: ((bosh_url)):((bosh_oauth_port))
      deployment_name: redis
      instance_name: ((on_demand_service_instance_name))
      version: ((bosh_version))
    cloudfoundry:
      url: ((system_domain))
      sslSkipValidation: true
      admin:
        id: ((paasta_admin_username))
        password: ((paasta_admin_password))
  mariadb:                                                    # MARIA DB SERVER 설정 정보
    port: ((mariadb_port))                                  # MARIA DB PORT 번호
    admin_user:
      password: ((mariadb_user_password))                   # MARIA DB ROOT 계정 비밀번호
    host_names:
    - mariadb0
######### SERVICE PROPERTIES #################
  service:
    password: ((service_password))
    port: ((service_port))
